[package]
name = "ezex_protos"
version = "0.1.0"
edition = "2021"

[dependencies]
prost = "0.11"
tonic = { version = "0.8", features = ["transport"] }

[build-dependencies]
prost-build = "0.11"
tonic-build = "0.8"
