// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: notification.proto

package notification

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SendTemplatedEmailRequest struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	Recipient    string                 `protobuf:"bytes,1,opt,name=recipient,proto3" json:"recipient,omitempty"`
	Subject      string                 `protobuf:"bytes,2,opt,name=subject,proto3" json:"subject,omitempty"`
	TemplateName string                 `protobuf:"bytes,3,opt,name=template_name,json=templateName,proto3" json:"template_name,omitempty"`
	// template_fields is a map of fields that generates body of an email inside a template
	TemplateFields map[string]string `protobuf:"bytes,4,rep,name=template_fields,json=templateFields,proto3" json:"template_fields,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SendTemplatedEmailRequest) Reset() {
	*x = SendTemplatedEmailRequest{}
	mi := &file_notification_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendTemplatedEmailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendTemplatedEmailRequest) ProtoMessage() {}

func (x *SendTemplatedEmailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_notification_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendTemplatedEmailRequest.ProtoReflect.Descriptor instead.
func (*SendTemplatedEmailRequest) Descriptor() ([]byte, []int) {
	return file_notification_proto_rawDescGZIP(), []int{0}
}

func (x *SendTemplatedEmailRequest) GetRecipient() string {
	if x != nil {
		return x.Recipient
	}
	return ""
}

func (x *SendTemplatedEmailRequest) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *SendTemplatedEmailRequest) GetTemplateName() string {
	if x != nil {
		return x.TemplateName
	}
	return ""
}

func (x *SendTemplatedEmailRequest) GetTemplateFields() map[string]string {
	if x != nil {
		return x.TemplateFields
	}
	return nil
}

type SendTemplatedEmailResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Recipient     string                 `protobuf:"bytes,1,opt,name=recipient,proto3" json:"recipient,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendTemplatedEmailResponse) Reset() {
	*x = SendTemplatedEmailResponse{}
	mi := &file_notification_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendTemplatedEmailResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendTemplatedEmailResponse) ProtoMessage() {}

func (x *SendTemplatedEmailResponse) ProtoReflect() protoreflect.Message {
	mi := &file_notification_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendTemplatedEmailResponse.ProtoReflect.Descriptor instead.
func (*SendTemplatedEmailResponse) Descriptor() ([]byte, []int) {
	return file_notification_proto_rawDescGZIP(), []int{1}
}

func (x *SendTemplatedEmailResponse) GetRecipient() string {
	if x != nil {
		return x.Recipient
	}
	return ""
}

var File_notification_proto protoreflect.FileDescriptor

const file_notification_proto_rawDesc = "" +
	"\n" +
	"\x12notification.proto\x12\fnotification\"\xa1\x02\n" +
	"\x19SendTemplatedEmailRequest\x12\x1c\n" +
	"\trecipient\x18\x01 \x01(\tR\trecipient\x12\x18\n" +
	"\asubject\x18\x02 \x01(\tR\asubject\x12#\n" +
	"\rtemplate_name\x18\x03 \x01(\tR\ftemplateName\x12d\n" +
	"\x0ftemplate_fields\x18\x04 \x03(\v2;.notification.SendTemplatedEmailRequest.TemplateFieldsEntryR\x0etemplateFields\x1aA\n" +
	"\x13TemplateFieldsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\":\n" +
	"\x1aSendTemplatedEmailResponse\x12\x1c\n" +
	"\trecipient\x18\x01 \x01(\tR\trecipient2\x80\x01\n" +
	"\x13NotificationService\x12i\n" +
	"\x12SendTemplatedEmail\x12'.notification.SendTemplatedEmailRequest\x1a(.notification.SendTemplatedEmailResponse\"\x00B/Z-github.com/ezex-io/ezex-proto/go/notificationb\x06proto3"

var (
	file_notification_proto_rawDescOnce sync.Once
	file_notification_proto_rawDescData []byte
)

func file_notification_proto_rawDescGZIP() []byte {
	file_notification_proto_rawDescOnce.Do(func() {
		file_notification_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_notification_proto_rawDesc), len(file_notification_proto_rawDesc)))
	})
	return file_notification_proto_rawDescData
}

var file_notification_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_notification_proto_goTypes = []any{
	(*SendTemplatedEmailRequest)(nil),  // 0: notification.SendTemplatedEmailRequest
	(*SendTemplatedEmailResponse)(nil), // 1: notification.SendTemplatedEmailResponse
	nil,                                // 2: notification.SendTemplatedEmailRequest.TemplateFieldsEntry
}
var file_notification_proto_depIdxs = []int32{
	2, // 0: notification.SendTemplatedEmailRequest.template_fields:type_name -> notification.SendTemplatedEmailRequest.TemplateFieldsEntry
	0, // 1: notification.NotificationService.SendTemplatedEmail:input_type -> notification.SendTemplatedEmailRequest
	1, // 2: notification.NotificationService.SendTemplatedEmail:output_type -> notification.SendTemplatedEmailResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_notification_proto_init() }
func file_notification_proto_init() {
	if File_notification_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_notification_proto_rawDesc), len(file_notification_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_notification_proto_goTypes,
		DependencyIndexes: file_notification_proto_depIdxs,
		MessageInfos:      file_notification_proto_msgTypes,
	}.Build()
	File_notification_proto = out.File
	file_notification_proto_goTypes = nil
	file_notification_proto_depIdxs = nil
}
